require("plugins.oil")
require("plugins.telescope")
require("plugins.blink")
require("plugins.miniharp")
require("plugins.whichkey")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.treesitter-context")
require("plugins.quickscope")
require("plugins.conform")
require("plugins.git")
require("plugins.grugfar")
require("plugins.lualine")

require("plugins.theme")
