-- vim.pack.add({
--   {
--     src = "https://github.com/nvim-lua/plenary.nvim",
--     name = "plenary.nvim",
--   },
--   {
--     src = "https://github.com/nvim-telescope/telescope-fzf-native.nvim",
--     name = "telescope-fzf-native",
--   },
--   {
--     src = "https://github.com/nvim-telescope/telescope.nvim",
--     name = "telescope",
--     version = vim.version.range("v*"), -- latest stable release
--   }
-- })
--
-- local telescope = require("telescope")
-- local builtin = require("telescope.builtin")
--
-- telescope.setup({
--   defaults = require("telescope.themes").get_ivy(),
--   extensions = {
--     fzf = {},
--   },
-- })
--
-- local fzf_path = vim.fn.stdpath("data") .. "/site/pack/core/opt/telescope-fzf-native"
-- local fzf_binary = fzf_path .. "/build/libfzf.so"
--
-- if vim.uv.fs_stat(fzf_binary) == nil then
--   print("Telescope-fzf-native binary not found. Compiling...")
--
--   local output = vim.fn.system({ "make", "-C", fzf_path })
--
--   if vim.v.shell_error ~= 0 then
--     vim.notify("Failed to compile telescope-fzf-native:\n" .. output, vim.log.levels.ERROR)
--   else
--     vim.notify("Successfully compiled telescope-fzf-native!", vim.log.levels.INFO)
--   end
-- end
--
-- telescope.load_extension("fzf")
--
-- vim.keymap.set("n", "<leader>ff", builtin.find_files, { desc = "find files" })
-- vim.keymap.set("n", "<leader>fb", builtin.buffers, { desc = "search buffers" })
-- vim.keymap.set("n", "<leader>fh", builtin.help_tags, { desc = "search help tags" })
-- vim.keymap.set("n", "<leader>fg", builtin.git_files, { desc = "search git files" })
--
-- vim.keymap.set("n", "<leader>fn", function()
--   builtin.find_files({ cwd = vim.fn.stdpath("config") })
-- end, { desc = "search neovim config files" })
--
-- vim.keymap.set("n", "<leader>fp", function()
--   builtin.find_files({
--     cwd = vim.fn.stdpath("data") .. "/site/pack",
--   })
-- end, { desc = "search plugin info files" })
--
-- require("telescope.multigrep").setup()
